version: '3.8'

services:
    %%service%%:
        image: %%app%%-%%service%%
        volumes:
            - ../:/ws/dev:cached
            - modules:/ws/dev/%%app%%-%%service%%/node_modules 
            - pnpm-store:/home/node/pnpm/store
        command: sleep infinity
        hostname: "{{.Service.Name}}-{{.Node.Hostname}}"
        environment:
            NODE_ENV: "development"
        env_file:
            - ../.env
        deploy:
            resources:
                limits:
                    cpus: '2'
volumes:
    modules:
    pnpm-store:
