version: '3.8'

services:
    %%service%%:
        image: %%app%%-%%service%%
        volumes:
            - /home/bruni/nodejs/%%app%%-%%service%%:/ws/:cached
            - modules:/ws/%%app%%-%%service%%/node_modules 
            - pnpm-store:/home/node/pnpm/store
        command: sleep infinity
        hostname: "debug-{{.Service.Name}}-{{.Node.Hostname}}"
        environment:
            NODE_ENV: "development"
        deploy:
            resources:
                limits:
                    cpus: '2'
            replicas: 1
            placement:
                constraints:
                    - node.hostname == moby1
            labels:
                traefik.enable: 'true'
                traefik.http.routers.debug-%%app%%-%%service%%.entrypoints: 'websecure'
                traefik.http.routers.debug-%%app%%-%%service%%.rule: "Host(`FQDN.it`) && (Headers(`LEDS_DEBUG`, `1`) || HeadersRegexp(`Cookie`, `LEDS_DEBUG=1`))"
                traefik.http.routers.debug-%%app%%-%%service%%.middlewares: "gzip@file"
                traefik.http.services.debug-%%app%%-%%service%%.loadbalancer.server.port: '80'
                traefik.http.services.debug-%%app%%-%%service%%.loadbalancer.server.scheme: 'http'
                traefik.http.routers.debug-%%app%%-%%service%%.tls: 'true'
volumes:
    modules:
    pnpm-store:
