version: '3.8'

services:
    %%service%%:
        image: %%app%%-%%service%%
        volumes:
            - ../%%app%%-%%service%%:/ws/%%app%%-%%service%%:cached
            - modules:/ws/%%app%%-%%service%%/node_modules 
            - pnpm-store:/home/node/pnpm/store
        command: sleep infinity
        hostname: "debug-{{.Service.Name}}-{{.Node.Hostname}}"
        environment:
            NODE_ENV: "development"
        deploy:
            resources:
                limits:
                    cpus: '2'
volumes:
    modules:
    pnpm-store:
